---
title: iCal4j Actions Framework
---
classDiagram
    direction LR

    class Trigger~T extends Serializable~
    Trigger~T~: URI context
    Trigger~T~: T source
    Trigger~T~: TriggerType type
    Trigger~T~: Instant timestamp

    class TriggerType
    <<enumeration>> TriggerType
    TriggerType: Timer
    TriggerType: Creation
    TriggerType: Update
    TriggerType: Deletion

    class TriggerSubscriber~T extends Serializable~
    TriggerSubscriber~T extends Serializable~: Flow.Subscription subscription
    TriggerSubscriber~T extends Serializable~: TriggerHandler~T~ handler

    class TriggerHandler~T extends Serializable~
    <<interface>> TriggerHandler~T extends Serializable~
    TriggerHandler~T extends Serializable~: onTrigger(Trigger~T~ trigger)

    class WorkflowProcessor~T extends Serializable~
    WorkflowProcessor~T extends Serializable~: List~VToDo~ actions

    class TaskGenerator~T extends Serializable~
    <<interface>> TaskGenerator~T extends Serializable~
    TaskGenerator~T extends Serializable~: generate(Trigger~T~ trigger) List~VToDo~

    class RecurringTaskGenerator
    RecurringTaskGenerator: VToDo action

    class ConditionalTaskGenerator
    ConditionalTaskGenerator: VToDo action

    TriggerHandler~T extends Serializable~ <|.. WorkflowProcessor~T extends Serializable~: Implements

    TaskGenerator~T extends Serializable~ <|.. RecurringTaskGenerator: Implements
    TaskGenerator~T extends Serializable~ <|.. ConditionalTaskGenerator: Implements
