mindmap
  root((iCal4j Core))
    iCal4j vCard
        p)vCard Model Extensions(
    iCal4j Extensions
        p)Strategies and Model Extensions(
    iCal4j Serializer
        p)XML/JSON Marshaling(
    iCal4j Connector
        p)Storage Interfaces(
    iCal4j Integration
        p)Email and Messaging(
    iCal4j Command
        p)Command Line Tools(
    iCal4j Streams
        p)Data-driven Workflows(
    iCal4j Graph
        p)Linked Object Traversal(
    iCal4j Template
        p)Content Rendering(

