mindmap
  root((iCal4j Core))
    iCal4j Extensions
        p)Model Extensions(
    iCal4j vCard
        p)vCard Model Extensions(
    iCal4j Template
        p)Creational Patterns(
    iCal4j Command
        p)Command Pattern(
    iCal4j Connector
        p)Persistence(
    iCal4j Integration
        p)Integration Patterns(
    iCal4j Streams
        p)Reactive Streams(
    iCal4j ZoneInfo Outlook
        p)Timezone Definitions(
    iCal4j Serializer
        p)XML/JSON(

