---
title: iCal4j Validation
---
classDiagram
    direction RL

    class Validator~T~
    <<Interface>> Validator~T~
    Validator~T~: validate(T target) ValidationResult

    class AbstractValidator~T~
    <<Abstract>> AbstractValidator~T~
    AbstractValidator~T~: List~AbstractValidationRuleSet~? super T~~ ruleSets

    class PropertyValidator~T extends Property~

    class ComponentValidator~T extends Component~

    ValidationResult: Set~ValidationEntry~ entries

    ValidationEntry: String message
    ValidationEntry: Severity severity
    ValidationEntry: String context

    ValidationRule~T~: ValidationType type
    ValidationRule~T~: String message
    ValidationRule~T~: Predicate~T~ predicate

    class AbstractValidationRuleSet~T~
    <<Abstract>> AbstractValidationRuleSet~T~
    AbstractValidationRuleSet~T~: Set~ValidationRule~? super T~~ rules

    class PropertyRuleSet~T extends Property~
    class PropertyContainerRuleSet~T extends PropertyContainer~
    class ComponentContainerRuleSet~ComponentContainer~

    Validator~T~ <|-- AbstractValidator~T~: Implements

    AbstractValidator~T~ <|-- PropertyValidator~T extends Property~: Inherits
    AbstractValidator~T~ <|-- ComponentValidator~T extends Component~: Inherits

    AbstractValidationRuleSet~T~ <|-- PropertyRuleSet~T extends Property~: Inherits
    AbstractValidationRuleSet~T~ <|-- PropertyContainerRuleSet~T extends PropertyContainer~: Inherits
    AbstractValidationRuleSet~T~ <|-- ComponentContainerRuleSet~ComponentContainer~: Inherits
